name: Kernel Builder (E404)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
          
      - name: Clone Kernel Source
        run: |
          git clone https://github.com/Olzhas-Kdyr/kernel_xiaomi_sm8250 ${{ github.workspace }}/kernel_xiaomi_sm8250 --depth=1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flex bc bison gcc gcc-aarch64-linux-gnu ccache p7zip-full lld

      - name: Checkout AnyKernel3
        uses: actions/checkout@v4
        with:
          repository: olzhas0986/Anykernel3
          path: kernel_xiaomi_sm8250/AnyKernel3

      - name: Clone AOSP Clang && Build Kernel
        run: |
          cd kernel_xiaomi_sm8250
          git submodule update --init
          chmod +x build.sh
          ./build.sh
        env:
          TGTOKEN: ${{ secrets.TGTOKEN }}
          
